"""index sorry columns used by the analytics endpoints

Revision ID: 8f7763c80e19
Revises: e8bea6841fdb
Create Date: 2026-09-02 06:10:19.683393

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8f7763c80e19'
down_revision: Union[str, Sequence[str], None] = 'e8bea6841fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_challenge_sorry_id'), 'challenge', ['sorry_id'], unique=False)
    op.create_index(op.f('ix_sqlsorry_blame_date'), 'sqlsorry', ['blame_date'], unique=False)
    op.create_index(op.f('ix_sqlsorry_inclusion_date'), 'sqlsorry', ['inclusion_date'], unique=False)
    op.create_index(op.f('ix_sqlsorry_lean_version'), 'sqlsorry', ['lean_version'], unique=False)
    op.create_index(op.f('ix_sqlsorry_remote'), 'sqlsorry', ['remote'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sqlsorry_remote'), table_name='sqlsorry')
    op.drop_index(op.f('ix_sqlsorry_lean_version'), table_name='sqlsorry')
    op.drop_index(op.f('ix_sqlsorry_inclusion_date'), table_name='sqlsorry')
    op.drop_index(op.f('ix_sqlsorry_blame_date'), table_name='sqlsorry')
    op.drop_index(op.f('ix_challenge_sorry_id'), table_name='challenge')
    # ### end Alembic commands ###
