name: Generate OpenAPI Specification

on:
  push:
    branches: [ main ]
    paths:
      - 'sorrydb/leaderboard/api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'sorrydb/leaderboard/api/**'
  workflow_dispatch:

jobs:
  generate-openapi:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn sqlmodel pydantic typer
        
    - name: Generate OpenAPI specification
      run: |
        cd leaderboard_deployment
        python export_openapi_spec.py --output ../openapi.json
        
    - name: Upload OpenAPI spec as artifact
      uses: actions/upload-artifact@v3
      with:
        name: openapi-spec
        path: openapi.json
        
    - name: Checkout SDK repository
      uses: actions/checkout@v4
      with:
        repository: SorryDB/sorrydb-api-sdk
        token: ${{ secrets.GITHUB_TOKEN }}
        path: sdk-repo
        
    - name: Copy OpenAPI spec to SDK repo
      run: |
        cp openapi.json sdk-repo/
        
    - name: Display SDK repo contents
      run: |
        echo "SDK repository contents:"
        ls -la sdk-repo/
        echo "OpenAPI spec preview:"
        head -20 sdk-repo/openapi.json
